### PR TITLE
feat: Add state machine widget

### PR DESCRIPTION
**Pull request by Sofia-Rommel**
### Summary 

Add the state machine widget

### Details 

Rocketsound state widget modified for Daedalus

### Additional information 

n/a

### Related links 

State Definitions: https://gitlab2.informatik.uni-wuerzburg.de/wuespace/daedalus2/software/schwarzes-brett/-/wikis/StateMachine 

### CLA

- [x] I have signed the individual contributor's license agreement **and sent** it to the board of the WüSpace e. V. organization.

---
This change is [Reviewable](https://reviewable.io/reviews/wuespace/telestion-project-daedalus2/90)

### CODE REVIEW

**Review by pklaschka — CHANGES_REQUESTED** [review]
> Reviewed 7 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/wuespace/telestion-project-daedalus2/90)* status: 7 of 9 files reviewed, 2 unresolved discussions (waiting on @fussel178 and @Sofia-Rommel)

*[a discussion](https://reviewable.io/reviews/wuespace/telestion-project-daedalus2/90#-Mcs7W2R7ETLabmPWGht:-Mcs7W2S344yGnncu2Tb:b-el2lpq) (no related file):*
Overall, it looks great. I've requested a minor change "inline" :wink:.

In the D2 project, channels will work a bit differently, meaning we probably won't have a `channels.ts`. Also, the format for messages (previously `DataMessage`) changed. It isn't a big change, meaning we can either.

1. merge this and then "just change it."
2. perhaps do it together after our team meeting so that you get a better overview of how it works

I'll leave that decision up to you, but will mark this as "requesting changes" as before we merge it, we should discuss how we want to proceed in regards to the question above :wink: 

---
___
*[client/src/widgets/state-widget/widget.tsx, line 260 at r1](https://reviewable.io/reviews/wuespace/telestion-project-daedalus2/90#-Mcs8vHZEPt7FIDmJO7t:-Mcs8vHZEPt7FIDmJO7u:b-v5m90u) ([raw file](https://github.com/wuespace/telestion-project-daedalus2/blob/dfac6536474bb1c1a46353d0d4c1d906f4c5ca85/client/src/widgets/state-widget/widget.tsx#L260)):*
> ```XML
> 	const current = useChannelLatest<FlightStateMessage>(FlightState);
> 
> 	if (current) console.log('Flightstate:', current.result[0].state);
> ```

Here, we can use the logger provided by the `telestion-client-core` library (https://wuespace.github.io/telestion-client/@wuespace/telestion-client-core/#useLogger) to get some scoped and semantic logging:

To do that, you can use something like this:

```ts
import {useLogger} from 'telestion-client-core';

[...]

const logger = useLogger('state-machine-widget');

if (current) logger.debug('Flightstate:', current.result[0].state);
```

**Review by pklaschka — COMMENTED** [review]
> Reviewed 2 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/wuespace/telestion-project-daedalus2/90)* status: all files reviewed, 2 unresolved discussions (waiting on @fussel178 and @Sofia-Rommel)

**Comment by Sofia-Rommel** [comment]
> > Reviewed 7 of 9 files at r1.
> > _[Reviewable](https://reviewable.io/reviews/wuespace/telestion-project-daedalus2/90)_ status: 7 of 9 files reviewed, 2 unresolved discussions (waiting on @fussel178 and @Sofia-Rommel)
> 
> _[a discussion](https://reviewable.io/reviews/wuespace/telestion-project-daedalus2/90#-Mcs7W2R7ETLabmPWGht:-Mcs7W2S344yGnncu2Tb:b-el2lpq) (no related file):_
> Overall, it looks great. I've requested a minor change "inline" 😉.
> 
> In the D2 project, channels will work a bit differently, meaning we probably won't have a `channels.ts`. Also, the format for messages (previously `DataMessage`) changed. It isn't a big change, meaning we can either.
> 
> 1. merge this and then "just change it."
> 2. perhaps do it together after our team meeting so that you get a better overview of how it works
> 
> I'll leave that decision up to you, but will mark this as "requesting changes" as before we merge it, we should discuss how we want to proceed in regards to the question above 😉
> 
> _[client/src/widgets/state-widget/widget.tsx, line 260 at r1](https://reviewable.io/reviews/wuespace/telestion-project-daedalus2/90#-Mcs8vHZEPt7FIDmJO7t:-Mcs8vHZEPt7FIDmJO7u:b-v5m90u) ([raw file](https://github.com/wuespace/telestion-project-daedalus2/blob/dfac6536474bb1c1a46353d0d4c1d906f4c5ca85/client/src/widgets/state-widget/widget.tsx#L260)):_
> 
> > ```
> > 	const current = useChannelLatest<FlightStateMessage>(FlightState);
> > 
> > 	if (current) console.log('Flightstate:', current.result[0].state);
> > ```
> 
> Here, we can use the logger provided by the `telestion-client-core` library (https://wuespace.github.io/telestion-client/@wuespace/telestion-client-core/#useLogger) to get some scoped and semantic logging:
> 
> To do that, you can use something like this:
> 
> ```ts
> import {useLogger} from 'telestion-client-core';
> 
> [...]
> 
> const logger = useLogger('state-machine-widget');
> 
> if (current) logger.debug('Flightstate:', current.result[0].state);
> ```

Are these changes still applicable / needed after @fussel178 changed the widget to make it compatible?

**Review by fussel178 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/wuespace/telestion-project-daedalus2/90)* status: 2 of 18 files reviewed, 2 unresolved discussions (waiting on @fussel178, @pklaschka, and @Sofia-Rommel)

*[a discussion](https://reviewable.io/reviews/wuespace/telestion-project-daedalus2/90#-Mcs7W2R7ETLabmPWGht:-Mghi7sX6mOeZsWavOh_:ba8uqj9) (no related file):*
<details><summary><i>Previously, pklaschka (Pablo Klaschka) wrote…</i></summary><blockquote>

Overall, it looks great. I've requested a minor change "inline" :wink:.

In the D2 project, channels will work a bit differently, meaning we probably won't have a `channels.ts`. Also, the format for messages (previously `DataMessage`) changed. It isn't a big change, meaning we can either.

1. merge this and then "just change it."
2. perhaps do it together after our team meeting so that you get a better overview of how it works

I'll leave that decision up to you, but will mark this as "requesting changes" as before we merge it, we should discuss how we want to proceed in regards to the question above :wink: 
</blockquote></details>

Introduced new message types and channel names and cleaned up the state widget using the new types and channels.

---

**Review by pklaschka — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/wuespace/telestion-project-daedalus2/90)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cb0s)

**Pull request merged**
